%YAML:1.0


# BA_solver
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 50   # max solver itrations, to guarantee real time
lossfunction_type: 0            # 损失核函数类型， 0 : 不适用损失核函数， 1 : Cauchy核函数 2 ：Huber, 3 ： Tukey
delta: 1.0                       #使用损失核函数的参数
num_of_thread: 1
num_of_cam: 1
progress_to_stdout: 1
window_size: 10
stereo: 0
point_type: 1   # 地图点表示形式，0 ： 表示逆深度表示形式，1 ： 表示3D表示形式，默认使用逆深度表示形式。
problem_type: 0 # 优化问题类型， 0： 表示BA问题， 1 ： 表示PoseGraph问题，默认是BA问题





