Iterations: 5000
Mean: -4.0
Var: 0.0
Poses:
  -
    Idx: 0
    R: [0.0,  90.0,  0.0]
    t: [0.0,  0.0,  0.0]
  -
    Idx: 1
    R: [0.0,  90.0,  0.0]
    t: [1.0,  0.0,  0.0]
  -
    Idx: 2
    R: [0.0,  90.0,  0.0]
    t: [0.0,  1.0,  0.0]
  -
    Idx: 3
    R: [0.0,  90.0,  0.0]
    t: [0.0,  0.0,  1.0]    
  -
    Idx: 4
    R: [0.0,  90.0,  0.0]
    t: [1.0,  1.0,  0.0]
  -
    Idx: 5
    R: [0.0,  90.0,  0.0]
    t: [0.0,  1.0,  1.0]
  -
    Idx: 6
    R: [0.0,  90.0,  0.0]
    t: [1.0,  0.0,  1.0]
  -
    Idx: 7
    R: [0.0,  90.0,  0.0]
    t: [1.0,  1.0,  1.0]    
  -
    Idx: 8
    R: [0.0,  90.0,  0.0]
    t: [1.0,  0.5,  0.1]
  -
    Idx: 9
    R: [0.0,  90.0,  0.0]
    t: [0.1,  0.5,  1.0]

Lines:
  -
    Idx: 0
    StartPt: [2.0,  0.0,  2.0]
    EndPt: [2.0,  1.0,  3.0]
  -
    Idx: 1
    StartPt: [3.0,  0.0,  4.0]
    EndPt: [3.0,  2.0,  6.0]
  -
    Idx: 2
    StartPt: [4.0,  1.0,  2.0]
    EndPt: [4.0,  2.0,  3.0]
  -
    Idx: 3
    StartPt: [5.0,  2.0,  4.0]
    EndPt: [5.0,  4.0,  6.0]
  -
    Idx: 4
    StartPt: [6.0,  3.0,  4.0]
    EndPt: [6.0,  4.0,  5.0]
  -
    Idx: 5
    StartPt: [7.0,  5.0,  4.0]
    EndPt: [7.0,  10.0,  9.0]    