Iterations: 10000
Mean: -2.5
Var: 0.0
Poses:
  -
    Idx: 0
    R: [0.0,  90.0,  0.0]
    t: [0.0,  0.0,  0.0]
  -
    Idx: 1
    R: [0.0,  90.0,  0.0]
    t: [1.0,  0.0,  0.0]
  -
    Idx: 2
    R: [0.0,  90.0,  0.0]
    t: [0.0,  1.0,  0.0]
  -
    Idx: 3
    R: [0.0,  90.0,  0.0]
    t: [0.0,  0.0,  1.0]    
  -
    Idx: 4
    R: [0.0,  90.0,  0.0]
    t: [1.0,  1.0,  0.0]
  -
    Idx: 5
    R: [0.0,  90.0,  0.0]
    t: [0.0,  1.0,  1.0]
  -
    Idx: 6
    R: [0.0,  90.0,  0.0]
    t: [1.0,  0.0,  1.0]
  -
    Idx: 7
    R: [0.0,  90.0,  0.0]
    t: [1.0,  1.0,  1.0]    
  -
    Idx: 8
    R: [0.0,  90.0,  0.0]
    t: [1.0,  0.5,  0.1]
  -
    Idx: 9
    R: [0.0,  90.0,  0.0]
    t: [0.1,  0.5,  1.0]

Points:
  -
    Idx: 0
    Point: [2.0,  1.0,  3.0]
  -
    Idx: 1
    Point: [2.0,  0.0,  3.0]
  -
    Idx: 2
    Point: [2.0,  1.0,  3.0]
  -
    Idx: 3
    Point: [3.0,  1.0,  10.0]
  -
    Idx: 4
    Point: [3.0,  0.0,  10.0]
  -
    Idx: 5
    Point: [3.0,  1.0,  10.0]    
  -
    Idx: 6
    Point: [3.0,  0.0,  4.0]    
  -
    Idx: 7
    Point: [2.0,  0.0,  2.0]    